### PR TITLE
refactor(BaseConfigurationBase): Remove not needed car Priorities

### PR DESCRIPTION
**Pull request by pkuehnel**

### CODE REVIEW

**Comment by fprucker** [comment]
Documentation README needs to be updated to reflect this change. Thanks a lot!

**Comment by fprucker** [comment]
Also, regarding the configuration:
"If there is not enough power for all cars the cars with higher priority get charged first. If multiple cars have the same priority the order will be random."
Does that mean the car with the higher VALUE has priority; e.g. if car A is set to 1 and car B to 0, car A would have priority?

**Comment by pkuehnel** [comment]
Yes. But as I am reading that it by myself... It is a little bit confusing, isn't it? Priority 1 should be higher than 2. 🤔

Regarding README documentation: I won't update it for now, as I want to make these things clear within the application itself. With more hints for everything and so on. Best documentation is the one you don't need ;-) 
But feel free to update the README and create a pull request, I would be happy to see you on the [Contributors page](https://github.com/pkuehnel/TeslaSolarCharger/graphs/contributors) ;-)

**Comment by fprucker** [comment]
Thanks for confirming and yes, I think it is confusing. Lowest number should be highest priority (and, to make it even more clear, start with 1 (=first) and not with 0.

Depending on whether you will make the change I suggest above I am happy to update the README thereafter and become a contributor :-)

**Comment by fprucker** [comment]
related idea, what do you think about dropping the hard-coded priorities and replace by SoC?

**Comment by pkuehnel** [comment]
@fprucker I created a new issue for both ideas: https://github.com/pkuehnel/TeslaSolarCharger/issues/513

**Pull request merged**
