### PR TITLE
feat/weekdaycharging

### PR DESCRIPTION
**Pull request by pkuehnel**

### CODE REVIEW

**Comment by pkuehnel** [comment]
@b1ggi Unit tests seem to fail. If you resolve that, I will create a release to test the feature.

**Comment by b1ggi** [comment]
Fix for failed tests in PR https://github.com/pkuehnel/TeslaSolarCharger/pull/1342

**Comment by pkuehnel** [comment]
@b1ggi You can now test everything using `:weekdaycharging` as tag instead of `:latest`.

**Comment by pkuehnel** [comment]
@b1ggi I think that is not a weekdaycharging specific bug, but thanks in advance for resolving it.

**Comment by pkuehnel** [comment]
@b1ggi due to various overlapping changes I needed to rebase the branch onto develop. Please use the latest version for your fixes.

**Comment by pkuehnel** [comment]
@b1ggi Just noticed that due to my rebase all commits are counted for me so you need to make another commit to be mentioned as a contributor -.-

**Comment by pkuehnel** [comment]
@b1ggi needed to reabase again, sorry. I just released again without that feature, can you tell me when you are ready and everything is tested?

**Comment by b1ggi** [comment]
@pkuehnel i tested the feature now for 1 month (i recently also installed a 32kwh diy-battery) and it works like expected, and im very happy with the feature, it really helps to optimize charging for a normal Mo-Fr week.

It would be nice if it would be possible to select specific Days to charge, but if there is no demand, i think were good.

I cannot reproduce the bug i mentioned above, i think it was a browser cache problem after updating.

**Comment by pkuehnel** [comment]
As I needed to fix a few merge conflicts you won't be displayed as contributor. If you want to be displayed (And to be honest I want the list of contributors to be complete), create a fork from [this branch](https://github.com/pkuehnel/TeslaSolarCharger/tree/feat/addOptionToChargeOnlyOnWeekDays) and remove the first line of [this file](https://github.com/pkuehnel/TeslaSolarCharger/blob/feat/addOptionToChargeOnlyOnWeekDays/TeslaSolarCharger.Model/Entities/TeslaSolarCharger/Car.cs).

**Comment by b1ggi** [comment]
https://github.com/b1ggi/TeslaSolarCharger/tree/feat/addOptionToChargeOnlyOnWeekDays
I did, correct like this?

**Comment by pkuehnel** [comment]
@b1ggi You can now update to `:edge`. This is the latest alpha release, including your weekday charging feature. When the next version is released, your feature will be included. Thanks a lot.

**Comment by b1ggi** [comment]
is it possible to go back to the public release from edge? i know how to do it, just if there are known problems if i do this.

**Comment by pkuehnel** [comment]
Yes, just make sure to pull the latest `:latest` version.

**Pull request merged**
